[package]
name = "conque"
version = "0.0.0-alpha"
edition = "2021"
authors = ["ETKNeil tehtris_github[at]protonmail[dot]com"]
license = "Unlicense"
description = "Placeholder to avoid name shadowing"

[dependencies]
